#!/bin/bash
#
# Patchwork - automated patch tracking system
# Copyright (C) 2010 Jeremy Kerr <jk@ozlabs.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

TOOLS_DIR="$(dirname "$0")"
PW_DIR="${TOOLS_DIR}/../patchwork"

if [ "$#" -lt 1 ]; then
    echo "usage: $0 <revspec>" >&2
    exit 1
fi

get_patchwork_hash() {
    local hash

    hash=$(git show -s --format='%(trailers)' "$1" | sed -n -e 's/^Change-Id: \(.*\)$/\1/p')
    if test -z "$hash"; then
	hash=$(git diff "$1~..$1" | python $PW_DIR/hasher.py)
    fi
    echo "$hash"
    test -n "$hash"
}

git rev-list --reverse "$@" |
while read -r commit; do
    hash=$(get_patchwork_hash "$commit")
    pwclient update -s Accepted -c "$commit" -h "$hash"
done
